In [1]:
import pandas as pd

In [3]:
data = {
    "Student_ID": [1, 2, 3, 4, 5],
    "Name": ['Alice', 'Bob', 'Charlie', 'David', 'Eva'],
    "Attendance": [85, 90, 78, 92, 88],
    "Final_Grade": ['A', 'B', 'C', 'A', 'B'],
    "Enrolled_Date": ['2024-01-10', '2024-02-15', '2024-01-25', '2024-03-01', '2024-01-20']
}
df = pd.DataFrame(data)
df

   Student_ID     Name  Attendance Final_Grade Enrolled_Date
0           1    Alice          85           A    2024-01-10
1           2      Bob          90           B    2024-02-15
2           3  Charlie          78           C    2024-01-25
3           4    David          92           A    2024-03-01
4           5      Eva          88           B    2024-01-20

In [4]:
print("Column names: ", df.columns)
print("Column data types: \n", df.dtypes)

Column names:  Index(['Student_ID', 'Name', 'Attendance', 'Final_Grade', 'Enrolled_Date'], dtype='object')
Column data types:
 Student_ID        int64
Name             object
Attendance        int64
Final_Grade      object
Enrolled_Date    object
dtype: object

In [8]:
df["Enrolled_Date"] = df["Enrolled_Date"].astype("datetime64[s]")
df["Enrolled_Date"]

0   2024-01-10
1   2024-02-15
2   2024-01-25
3   2024-03-01
4   2024-01-20
Name: Enrolled_Date, dtype: datetime64[s]

In [9]:
df.dtypes

Student_ID               int64
Name                    object
Attendance               int64
Final_Grade             object
Enrolled_Date    datetime64[s]
dtype: object

In [10]:
df["Final_Grade"].unique()

array(['A', 'B', 'C'], dtype=object)

In [11]:
df["Final_Grade"] = df["Final_Grade"].astype("category")

In [12]:
df["Final_Grade_Encode"] = df["Final_Grade"].cat.codes + 1
df

,Student_ID,Name,Attendance,Final_Grade,Enrolled_Date,Final_Grade_Encode
0,1,Alice,85,A,2024-01-10,1
1,2,Bob,90,B,2024-02-15,2
2,3,Charlie,78,C,2024-01-25,3
3,4,David,92,A,2024-03-01,1
4,5,Eva,88,B,2024-01-20,2

In [17]:
Final_Grade_One_Hot_Encoding = pd.get_dummies(df["Final_Grade"])
Final_Grade_One_Hot_Encoding = Final_Grade_One_Hot_Encoding.astype(int)
df = pd.concat([df, Final_Grade_One_Hot_Encoding], axis=1)
df

,Student_ID,Name,Attendance,Final_Grade,Enrolled_Date,Final_Grade_Encode,A,B,C
0,1,Alice,85,A,2024-01-10,1,1,0,0
1,2,Bob,90,B,2024-02-15,2,0,1,0
2,3,Charlie,78,C,2024-01-25,3,0,0,1
3,4,David,92,A,2024-03-01,1,1,0,0
4,5,Eva,88,B,2024-01-20,2,0,1,0

In [20]:
Enrolled_Year = df["Enrolled_Date"].dt.year
Enrolled_Year

0    2024
1    2024
2    2024
3    2024
4    2024
Name: Enrolled_Date, dtype: int32